DROP TABLE IF EXISTS Categories;
CREATE TABLE IF NOT EXISTS Categories (
    CategoryId INTEGER PRIMARY KEY AUTOINCREMENT,
    Title VARCHAR(100) NOT NULL,
    ImgUrl VARCHAR(300) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP NOT NULL
);
DROP TABLE IF EXISTS Articles;
CREATE TABLE IF NOT EXISTS Articles (
    ArticleId INTEGER PRIMARY KEY AUTOINCREMENT,
    Title VARCHAR(100) NOT NULL,
    CategoryId INTEGER NOT NULL, 
    Content TEXT NOT NULL,
    ImgUrl VARCHAR(300) NOT NULL,
    ImgSource VARCHAR(100) NOT NULL,
    CreatedAt  TIMESTAMP NOT NULL,
    UpdatedAt  TIMESTAMP NOT NULL,
    FOREIGN KEY (CategoryId) REFERENCES Categories(CategoryId) ON DELETE CASCADE
);
DROP TABLE IF EXISTS Roles;
CREATE TABLE IF NOT EXISTS Roles (
    RoleId INTEGER  PRIMARY KEY AUTOINCREMENT, 
    Name VARCHAR(255) NOT NULL UNIQUE,
    SuperAdmin BOOLEAN NOT NULL DEFAULT 0,
    Description VARCHAR(255),
    CreatedAt TIMESTAMP,
    UpdatedAt TIMESTAMP
);
DROP TABLE IF EXISTS Permissions;
CREATE TABLE IF NOT EXISTS Permissions (
    PermissionId INTEGER  PRIMARY KEY AUTOINCREMENT,
    PermissionName VARCHAR(255) NOT NULL UNIQUE,
    Description VARCHAR(255),
    CreatedAt TIMESTAMP NOT NULL,
    UpdateAt TIMESTAMP NOT NULL
);
DROP TABLE IF EXISTS RolePermissions;
CREATE TABLE IF NOT EXISTS RolePermissions (
    RolePermissionId INTEGER PRIMARY KEY AUTOINCREMENT,
    RoleId INTEGER,
    PermissionId INTEGER,
    FOREIGN KEY (RoleId) REFERENCES Roles(RoleId),
    FOREIGN KEY (PermissionId) REFERENCES Permissions(PermissionId)
);
DROP TABLE IF EXISTS Users;
CREATE TABLE IF NOT EXISTS Users (
    UserId INTEGER PRIMARY KEY AUTOINCREMENT,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL,
    RoleId INTEGER,
    CreatedAt TIMESTAMP,
    UpdatedAt TIMESTAMP,
    FOREIGN KEY (RoleId) REFERENCES Roles(RoleId)
);
INSERT INTO Roles (Name,SuperAdmin,Description,CreatedAt,UpdatedAt) VALUES ('超级管理员',1,'超级管理员','1710478326661','1710478326661'); 
INSERT INTO Users (Username,Email,Password,RoleId,CreatedAt,UpdatedAt) VALUES ('admin','123@qq.com','8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92',1,'1710478326661','1710478326661'); 
