DROP TABLE IF EXISTS Articles;
CREATE TABLE IF NOT EXISTS Articles (
    ArticleId INTEGER PRIMARY KEY AUTOINCREMENT,
    Title VARCHAR(100) NOT NULL,
    CategoryId INTEGER NOT NULL, 
    Content TEXT NOT NULL,
    ImgUrl VARCHAR(300) NOT NULL,
    ImgSource VARCHAR(100) NOT NULL,
    CreatedAt  TIMESTAMP NOT NULL,
    UpdatedAt  TIMESTAMP NOT NULL,
    FOREIGN KEY (CategoryId) REFERENCES Categories(CategoryId) ON DELETE CASCADE
);
DROP TABLE IF EXISTS RolePermissions;
CREATE TABLE IF NOT EXISTS RolePermissions (
    RolePermissionId INTEGER PRIMARY KEY AUTOINCREMENT,
    RoleId INTEGER,
    PermissionId INTEGER,
    FOREIGN KEY (RoleId) REFERENCES Roles(RoleId),
    FOREIGN KEY (PermissionId) REFERENCES Permissions(PermissionId)
);
DROP TABLE IF EXISTS Users;
CREATE TABLE IF NOT EXISTS Users (
    UserId INTEGER PRIMARY KEY AUTOINCREMENT,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL,
    RoleId INTEGER,
    CreatedAt TIMESTAMP,
    UpdatedAt TIMESTAMP,
    FOREIGN KEY (RoleId) REFERENCES Roles(RoleId)
);

